name: CI - Snapshot
run-name: CI snapshot disparada por ${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  build_back:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
          
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Instalar dependências e buildar
        shell: bash
        run: |
          cd build/ci_cd_projeto/backend
          npm install
          npm run build
          
      - name: Upload artefato Backend
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: build/ci_cd_projeto/backend/dist

  build_front:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
          
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Instalar dependências e buildar
        shell: bash
        run: |
          cd build/ci_cd_projeto/frontend
          npm install
          npm run build
          
      - name: Upload artefato Frontend
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: build/ci_cd_projeto/frontend/dist

  empacotar:
    name: Empacotar e Criar Release
    needs: [build_back, build_front]
    runs-on: ubuntu-latest
    steps:
      - name: Download artefato Frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend
          
      - name: Download artefato Backend
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend
          
      - name: Compactar artefatos
        shell: bash
        run: |
          zip -r frontend.zip frontend/
          zip -r backend.zip backend/
          
      - name: Criar Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Release ${{ github.run_number }}"
          tag_name: "v1.0.${{ github.run_number }}"
          body: "Release automático gerado pela pipeline CI"
          files: |
            backend.zip
            frontend.zip
