name: Deploy / Atualizar Servidores
run-name: Deploy do artefato ${{ inputs.releasetag }} em ${{ inputs.ambiente }} disparada por ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      releasetag:
        description: "Nome do artefato/versão"
        type: string
        required: true
      ambiente:
        type: choice
        description: 'Ambiente'
        required: true
        default: 'TST'
        options:
        - TST
        - PRD

jobs:
  app_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download Backend
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/${{ github.event.inputs.releasetag }}"
          file: 'backend.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Frontend
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/${{ github.event.inputs.releasetag }}"
          file: 'frontend.zip'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Descompacta Zips
        run: |
          mkdir backend frontend
          unzip backend.zip -d backend
          unzip frontend.zip -d frontend

      - name: Extrai IP do destino
        run: |
          echo "HOST=$(echo ${{ secrets.URL_TST }} | sed 's/.*@//')" >> $GITHUB_ENV

      - name: Baixa KeyPair e Adiciona ao known_hosts
        run: |
          set -e
          # Cria chave privada de forma segura
          printf '%s\n' "${{ secrets.KEYPAR_RSA }}" > keypair.pem
          chmod 400 keypair.pem
          
          # Cria pasta SSH e adiciona host ao known_hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Atualiza em TST
        if: ${{ inputs.ambiente == 'TST' }}
        run: |
          rsync -e "ssh -i keypair.pem" -avz backend/* ${{ secrets.URL_TST }}:${{ secrets.PASTA_PROJETO }}/tst/backend
          rsync -e "ssh -i keypair.pem" -avz frontend/* ${{ secrets.URL_TST }}:${{ secrets.PASTA_PROJETO }}/tst/frontend

      - name: Atualiza em PRD
        if: ${{ inputs.ambiente == 'PRD' }}
        run: |
          rsync -e "ssh -i keypair.pem" -avz backend/* ${{ secrets.URL_PRD }}:${{ secrets.PASTA_PROJETO }}/prd/backend
          rsync -e "ssh -i keypair.pem" -avz frontend/* ${{ secrets.URL_PRD }}:${{ secrets.PASTA_PROJETO }}/prd/frontend
